export const scoringCriteria = [
  
  // Female Pushup <25
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 19.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 19.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 19.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 16.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 16.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 16.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 14.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 23,
    maxPerformanceValue: 23,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 22,
    maxPerformanceValue: 22,
    points: 12.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 21,
    maxPerformanceValue: 21,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 20,
    maxPerformanceValue: 20,
    points: 11.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 19,
    maxPerformanceValue: 19,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 18,
    maxPerformanceValue: 18,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 17,
    maxPerformanceValue: 17,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 16,
    maxPerformanceValue: 16,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 15,
    maxPerformanceValue: 15,
    points: 1,
  },

   // Female Pushup 25-29
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 19.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 19.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 19.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 16.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 16.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 16.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 14.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 23,
    maxPerformanceValue: 23,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 22,
    maxPerformanceValue: 22,
    points: 12.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 21,
    maxPerformanceValue: 21,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 20,
    maxPerformanceValue: 20,
    points: 11.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 19,
    maxPerformanceValue: 19,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 18,
    maxPerformanceValue: 18,
    points: 10.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 17,
    maxPerformanceValue: 17,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 16,
    maxPerformanceValue: 16,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 15,
    maxPerformanceValue: 15,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 14,
    maxPerformanceValue: 14,
    points: 1,
  },

   // Female Pushup 30-34
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 19.9,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 19.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 19.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 19.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 18.7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 18.3,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 17.9,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 17.3,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 16.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 23,
    maxPerformanceValue: 23,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 22,
    maxPerformanceValue: 22,
    points: 15.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 21,
    maxPerformanceValue: 21,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 20,
    maxPerformanceValue: 20,
    points: 15.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 19,
    maxPerformanceValue: 19,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 18,
    maxPerformanceValue: 18,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 17,
    maxPerformanceValue: 17,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 16,
    maxPerformanceValue: 16,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 15,
    maxPerformanceValue: 15,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 14,
    maxPerformanceValue: 14,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 13,
    maxPerformanceValue: 13,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 12,
    maxPerformanceValue: 12,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 11,
    maxPerformanceValue: 11,
    points: 1,
  },
   // Female Pushup 35-39
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 19.7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 18.7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 18.3,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 18.1,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 17.9,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 17.3,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 23,
    maxPerformanceValue: 23,
    points: 16.4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 22,
    maxPerformanceValue: 22,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 21,
    maxPerformanceValue: 21,
    points: 15.8,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 20,
    maxPerformanceValue: 20,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 19,
    maxPerformanceValue: 19,
    points: 15.2,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 18,
    maxPerformanceValue: 18,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 17,
    maxPerformanceValue: 17,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 16,
    maxPerformanceValue: 16,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 15,
    maxPerformanceValue: 15,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 14,
    maxPerformanceValue: 14,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 13,
    maxPerformanceValue: 13,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 12,
    maxPerformanceValue: 12,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 11,
    maxPerformanceValue: 11,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 10,
    maxPerformanceValue: 10,
    points: 1,
  },

  // Male Pushup <25
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 67,
    maxPerformanceValue: 67,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 66,
    maxPerformanceValue: 66,
    points: 19.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 65,
    maxPerformanceValue: 65,
    points: 19.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 64,
    maxPerformanceValue: 64,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 63,
    maxPerformanceValue: 63,
    points: 19.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 62,
    maxPerformanceValue: 62,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 61,
    maxPerformanceValue: 61,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 60,
    maxPerformanceValue: 60,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 59,
    maxPerformanceValue: 59,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 58,
    maxPerformanceValue: 58,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 57,
    maxPerformanceValue: 57,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 56,
    maxPerformanceValue: 56,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 55,
    maxPerformanceValue: 55,
    points: 17.7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 16.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 16.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 15.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 14.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 12.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 11.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 10.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 1,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 62,
    maxPerformanceValue: 62,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 61,
    maxPerformanceValue: 61,
    points: 19.7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 60,
    maxPerformanceValue: 60,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 59,
    maxPerformanceValue: 59,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 58,
    maxPerformanceValue: 58,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 57,
    maxPerformanceValue: 57,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 56,
    maxPerformanceValue: 56,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 55,
    maxPerformanceValue: 55,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 17.5,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 16.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 16.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 15.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 14.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 12.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 11.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 10.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 1,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 57,
    maxPerformanceValue: 57,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 56,
    maxPerformanceValue: 56,
    points: 19.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 55,
    maxPerformanceValue: 55,
    points: 19.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 19.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 19.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 18.5,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 15.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 13.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 10.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 1,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 20,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 19.5,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 19,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 18.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 18.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 18.5,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 18.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 18.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 18,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 17.8,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 17.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 17.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 17.2,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 17,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 16.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 16,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 15.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 15.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 15,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 14.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 14,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 13.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 13.4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 13,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 12,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 11,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 10.6,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 10,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 23,
    maxPerformanceValue: 23,
    points: 7,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 22,
    maxPerformanceValue: 22,
    points: 4,
  },
  {
    exercise: 'pushup',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 21,
    maxPerformanceValue: 21,
    points: 1,
  },

  
  // Situp
 
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 57,
    maxPerformanceValue: 57,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 56,
    maxPerformanceValue: 56,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 55,
    maxPerformanceValue: 55,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 18.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 17.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 12.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 58,
    maxPerformanceValue: 58,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 56,
    maxPerformanceValue: 56,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 55,
    maxPerformanceValue: 55,
    points: 19.5,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 18.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 17.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 12.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 18.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 17.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 18.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 17.4,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 3,
  },
 
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 54,
    maxPerformanceValue: 54,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 53,
    maxPerformanceValue: 53,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 52,
    maxPerformanceValue: 52,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 51,
    maxPerformanceValue: 51,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 17.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 17.2,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 15.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 13.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 50,
    maxPerformanceValue: 50,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 49,
    maxPerformanceValue: 49,
    points: 19.5,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 48,
    maxPerformanceValue: 48,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 47,
    maxPerformanceValue: 47,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 46,
    maxPerformanceValue: 46,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 17.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 17.2,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 15.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 14.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 13.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 12.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 45,
    maxPerformanceValue: 45,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 44,
    maxPerformanceValue: 44,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 16.4,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 15.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 13.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 3,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 43,
    maxPerformanceValue: 43,
    points: 20,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 42,
    maxPerformanceValue: 42,
    points: 19.7,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 41,
    maxPerformanceValue: 41,
    points: 19.4,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 40,
    maxPerformanceValue: 40,
    points: 19,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 39,
    maxPerformanceValue: 39,
    points: 18.8,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 38,
    maxPerformanceValue: 38,
    points: 18,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 37,
    maxPerformanceValue: 37,
    points: 17.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 36,
    maxPerformanceValue: 36,
    points: 17,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 35,
    maxPerformanceValue: 35,
    points: 16.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 34,
    maxPerformanceValue: 34,
    points: 16.4,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 33,
    maxPerformanceValue: 33,
    points: 16,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 32,
    maxPerformanceValue: 32,
    points: 15.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 31,
    maxPerformanceValue: 31,
    points: 15,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 30,
    maxPerformanceValue: 30,
    points: 14,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 29,
    maxPerformanceValue: 29,
    points: 13.6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 28,
    maxPerformanceValue: 28,
    points: 13,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 27,
    maxPerformanceValue: 27,
    points: 12,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 26,
    maxPerformanceValue: 26,
    points: 9,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 25,
    maxPerformanceValue: 25,
    points: 6,
  },
  {
    exercise: 'situp',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 24,
    maxPerformanceValue: 24,
    points: 3,
  },
 

  // Run

  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 0,
    maxPerformanceValue: 552,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 553,
    maxPerformanceValue: 574,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 575,
    maxPerformanceValue: 585,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 586,
    maxPerformanceValue: 598,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 599,
    maxPerformanceValue: 610,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 611,
    maxPerformanceValue: 623,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 624,
    maxPerformanceValue: 637,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 638,
    maxPerformanceValue: 651,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 652,
    maxPerformanceValue: 666,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 49,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 46.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 44,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 41,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 38,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '<25',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 0,
    maxPerformanceValue: 562,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 563,
    maxPerformanceValue: 585,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 586,
    maxPerformanceValue: 598,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 599,
    maxPerformanceValue: 610,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 611,
    maxPerformanceValue: 623,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 624,
    maxPerformanceValue: 637,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 638,
    maxPerformanceValue: 651,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 652,
    maxPerformanceValue: 666,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 49,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 46.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 44,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 41,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 38,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '25-29',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 0,
    maxPerformanceValue: 574,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 575,
    maxPerformanceValue: 598,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 599,
    maxPerformanceValue: 610,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 611,
    maxPerformanceValue: 623,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 624,
    maxPerformanceValue: 637,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 638,
    maxPerformanceValue: 651,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 652,
    maxPerformanceValue: 666,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 48,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 45.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 43,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 40.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 38,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '30-34',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 0,
    maxPerformanceValue: 584,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 585,
    maxPerformanceValue: 610,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 611,
    maxPerformanceValue: 623,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 624,
    maxPerformanceValue: 637,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 638,
    maxPerformanceValue: 651,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 652,
    maxPerformanceValue: 666,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 48,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 45.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 43,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 40.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 38,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'male',
    ageGroup: '35-39',
    minPerformanceValue: 1018,
    maxPerformanceValue: 1054,
    points: 35,
  },
 
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 0,
    maxPerformanceValue: 623,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 624,
    maxPerformanceValue: 651,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 652,
    maxPerformanceValue: 666,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 49,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 46,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 1018,
    maxPerformanceValue: 1054,
    points: 42.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 1055,
    maxPerformanceValue: 1094,
    points: 39,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '<25',
    minPerformanceValue: 1095,
    maxPerformanceValue: 1136,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 0,
    maxPerformanceValue: 637,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 638,
    maxPerformanceValue: 666,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 667,
    maxPerformanceValue: 682,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 53.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 52,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 50.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 49,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 1018,
    maxPerformanceValue: 1054,
    points: 45.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 1055,
    maxPerformanceValue: 1094,
    points: 42,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 1095,
    maxPerformanceValue: 1136,
    points: 38.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '25-29',
    minPerformanceValue: 1137,
    maxPerformanceValue: 1183,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 0,
    maxPerformanceValue: 651,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 652,
    maxPerformanceValue: 682,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 683,
    maxPerformanceValue: 698,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 52.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 51,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 49.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 1018,
    maxPerformanceValue: 1054,
    points: 47,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 1055,
    maxPerformanceValue: 1094,
    points: 44.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 1095,
    maxPerformanceValue: 1136,
    points: 42,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 1137,
    maxPerformanceValue: 1183,
    points: 38.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '30-34',
    minPerformanceValue: 1184,
    maxPerformanceValue: 1233,
    points: 35,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 0,
    maxPerformanceValue: 666,
    points: 60,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 667,
    maxPerformanceValue: 698,
    points: 59.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 699,
    maxPerformanceValue: 716,
    points: 59,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 717,
    maxPerformanceValue: 734,
    points: 58.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 735,
    maxPerformanceValue: 753,
    points: 58,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 754,
    maxPerformanceValue: 773,
    points: 57.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 774,
    maxPerformanceValue: 794,
    points: 57,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 795,
    maxPerformanceValue: 816,
    points: 56.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 817,
    maxPerformanceValue: 840,
    points: 56,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 841,
    maxPerformanceValue: 865,
    points: 55.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 866,
    maxPerformanceValue: 892,
    points: 55,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 893,
    maxPerformanceValue: 920,
    points: 54.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 921,
    maxPerformanceValue: 950,
    points: 54,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 951,
    maxPerformanceValue: 982,
    points: 52.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 983,
    maxPerformanceValue: 1017,
    points: 51,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1018,
    maxPerformanceValue: 1054,
    points: 49.5,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1055,
    maxPerformanceValue: 1094,
    points: 47,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1095,
    maxPerformanceValue: 1136,
    points: 44,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1137,
    maxPerformanceValue: 1183,
    points: 41,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1184,
    maxPerformanceValue: 1233,
    points: 38,
  },
  {
    exercise: '1.5_mile_run',
    gender: 'female',
    ageGroup: '35-39',
    minPerformanceValue: 1234,
    maxPerformanceValue: 1288,
    points: 35,
  },

];
