CREATE DATABASE IF NOT EXISTS cadet_management;

USE cadet_management;

CREATE TABLE Objectives (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(255),
    objective_number VARCHAR(10),
    description TEXT,
    bc ENUM('P1', 'P2', 'P3'),
    bcl ENUM('P1', 'P2', 'P3'),
    icl ENUM('P1', 'P2', 'P3'),
    scl ENUM('P1', 'P2', 'P3')
);

INSERT INTO Objectives (category, objective_number, description, bc, bcl, icl, scl) VALUES
('Training Objective 1 - DAF and AFROTC Grade Structure and Insignia', '1.1', 'Identify Dept. of Air Force enlisted grade structure by insignia and name.', 'Ka', NULL, NULL, NULL),
('Training Objective 1 - DAF and AFROTC Grade Structure and Insignia', '1.2', 'Identify Dept. of Air Force & Joint officer grade structure by insignia and name.', 'Ka', NULL, NULL, NULL),
('Training Objective 1 - DAF and AFROTC Grade Structure and Insignia', '1.3', 'Identify AFROTC grade structure.', 'Ka', NULL, NULL, NULL),
('Training Objective 2 - DAF and AFROTC Chain of Command', '2.1', 'List the current Dept. of Air Force and AFROTC chain of command.', 'Ka', NULL, NULL, NULL),
('Training Objective 2 - DAF and AFROTC Chain of Command', '2.2', 'Summarize the chain of command from the President of the United States to you as a cadet.', NULL, 'Kb', NULL, NULL),
('Training Objective 3 - AFROTC Cadet Honor Code', '3.1', 'Define each element of the AFROTC Cadet Honor Code.', NULL, 'Kb', NULL, NULL),
('Training Objective 3 - AFROTC Cadet Honor Code', '3.2', 'Recall procedures for reporting a suspected Cadet Honor Code violation.', 'Ka', NULL, NULL, NULL),
('Training Objective 3 - AFROTC Cadet Honor Code', '3.3', 'Describe common misconceptions and improper applications of the Cadet Honor Code.', NULL, 'Kb', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.1', 'Recall proper DAF customs and courtesies expected of cadets to peers, superiors, and subordinates.', 'Ka', 'Kb', 'P3', NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.2', 'Practice proper forms of saluting and recognize who and when to salute.', 'P1', 'P2', 'P3', NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.3', 'Practice reporting in/reporting out procedures.', 'P1', 'P2', 'P3', NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.4', 'Utilize the proper courtesies displayed during informal and formal activities.', 'P1', 'P2', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.5', 'Recall procedures for proper display of the flag.', 'Ka', 'Ka', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.6', 'Describe proper customs and courtesies for outdoor ceremonies.', 'Ka', 'Kb', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.7', 'Describe proper customs and courtesies for indoor ceremonies.', 'Ka', 'Ka', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.8', 'Paraphrase proper procedures for folding the flag.', 'Ka', 'Kb', NULL, NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.9', 'Demonstrate proper procedures for retreat.', 'P1', 'P2', 'P3', NULL),
('Training Objective 4 - DAF Customs and Courtesies', '4.10', 'Demonstrate proper procedures for reveille.', 'P1', 'P2', 'P3', NULL),
('Training Objective 5 - Military Ceremonies and Protocol', '5.1', 'Describe Dining-In and Dining-Out procedures and protocol.', 'Ka', NULL, 'Kb', NULL),
('Training Objective 5 - Military Ceremonies and Protocol', '5.2', 'Describe official ceremonies protocol and procedures (award ceremony, change of command, etc.).', 'Ka', 'Ka', 'Kb', NULL),
('Training Objective 6 - DAF Dress and Appearance Standards', '6.1', 'List when it is inappropriate to wear your uniform.', 'Ka', 'Ka', NULL, NULL),
('Training Objective 6 - DAF Dress and Appearance Standards', '6.2', 'Demonstrate proper DAF grooming standards.', 'P1', 'P2', 'P3', NULL),
('Training Objective 6 - DAF Dress and Appearance Standards', '6.3', 'Demonstrate proper AFROTC and DAF dress and appearance standards.', 'P1', 'P2', 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.1', 'Demonstrate drill fundamentals.', 'P1', 'P2', 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.2', 'Demonstrate individual drill instruction.', 'P1', NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.3', 'Demonstrate basic drill of the flight.', 'P1', NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.4', 'Demonstrate intermediate drill of the flight.', 'P1', NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.5', 'Demonstrate advanced drill of the flight.', 'P1', NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.6', 'Demonstrate proper guidon positioning, commands, and movements.', NULL, 'P2', 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.7', 'Demonstrate detail marching.', NULL, NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.8', 'Demonstrate squadron marching.', 'P1', NULL, 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.9', 'Demonstrate Open Ranks Inspection.', 'P1', 'P2', 'P3', NULL),
('Training Objective 7 - Drill Positions and Movements', '7.10', 'Demonstrate proper road guard procedures.', 'P1', NULL, 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.1', 'Demonstrate effective followership.', 'P1', 'P2', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.2', 'Demonstrate effective team leadership.', 'P1', 'P2', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.3', 'Demonstrate effective group leadership as POC-In-Charge.', NULL, 'P2', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.4', 'Demonstrate the principles of an effective debrief.', 'P1', 'P2', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.5', 'Recall the Airman''s Foundational Competencies.', 'Ka', 'Kb', 'Kb', 'Kb'),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.6', 'Employ risk management principles and execute operations safely.', 'P1', 'P2', 'P3', 'P3'),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.7', 'Understand how mission planning impacts performance in problem solving and completing a mission.', 'P2', 'P3', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.8', 'Demonstrate the essentials of effective mission debrief.', 'P2', 'P3', 'P3', NULL),
('Training Objective 8 - Effective Followership, Leadership, and Teamwork Skills', '8.9', 'Practice leadership evaluation using the Form 2.', 'Ka', 'Kb', 'P2', 'P3'),
('Training Objective 9 - Understand How the DAF Employs Warfighting Assets ', '9.1', 'Recall DAF contributions to the joint fight.', 'Ka', 'Kb', NULL, NULL),
('Training Objective 9 - Understand How the DAF Employs Warfighting Assets ', '9.2', 'Summarize DAF warfighting assets.', 'Ka', 'Kb', NULL, NULL),
('Training Objective 9 - Understand How the DAF Employs Warfighting Assets ', '9.3', 'Practice the application of DAF assets to the joint fight through a wargaming scenario or discussion.', 'P1', NULL, 'P2', 'P3'),
('Training Objective 10 - Expeditionary Skills', '10.1', 'Differentiate the different types of order and their uses.', NULL, 'Ka', 'Kb', NULL),
('Training Objective 10 - Expeditionary Skills', '10.2', 'Discuss the considerations for operating in secured and/or hostile environments.', NULL, 'Ka', 'Kb', NULL),
('Training Objective 10 - Expeditionary Skills', '10.3', 'Practice the application of AF assets to the joint fight through a wargaming scenario or discussion.', 'P1', NULL, 'P2', 'P3'),
('Training Objective 10 - Expeditionary Skills', '10.4', 'Respond to UXOs and IEDs.', 'P1', NULL, 'P2', 'P3'),
('Training Objective 10 - Expeditionary Skills', '10.5', 'Respond to identified Insider Threat/Active Shooter scenarios.', NULL, 'P1', 'P3', NULL),
('Training Objective 11 - Preparation for Active Duty', '11.1', 'Carry out the cadet mentoring program.', NULL, 'P1', 'P2', NULL),
('Training Objective 11 - Preparation for Active Duty', '11.2', 'Practice leadership/management skills in supervising the cadet corps.', NULL, 'P1', 'P2', NULL),
('Training Objective 11 - Preparation for Active Duty', '11.3', 'Practice proper feedback and performance evaluation skills.', NULL, 'P2', NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.4', 'Utilize the ACA during feedbacks.', NULL, 'P2', NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.5', 'Utilize writing/evaluating narrative statements.', 'P1', NULL, NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.6', 'Practice elements of OPBs/EPBs.', 'P1', NULL, NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.7', 'Practice Awards & Decorations.', 'P1', NULL, NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.8', 'Describe the appropriate usage of the indorsement format of the official memorandum.', 'Kb', NULL, NULL, NULL),
('Training Objective 11 - Preparation for Active Duty', '11.9', 'Describe the administrative requirement for E-publishing usage to locate pubs and forms.', 'Kb', NULL, NULL, NULL);
